"""initial schema

Revision ID: 8dc6cc630d93
Revises: 
Create Date: 2026-09-25 11:22:49.347928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc6cc630d93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('anchored_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_anchors_event_id'), 'audit_anchors', ['event_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_domain', sa.String(length=255), nullable=False),
    sa.Column('org_identifier', sa.String(length=128), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_uri', sa.String(length=512), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending','verified','rejected')", name='ck_orgs_verification_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_identifier')
    )
    op.create_index(op.f('ix_organizations_official_domain'), 'organizations', ['official_domain'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('did', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('holder','issuer','verifier','admin')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('active','inactive','locked')", name='ck_users_account_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_did'), 'users', ['did'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_uri', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('cid', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('nft_token_id', sa.String(length=128), nullable=True),
    sa.Column('chain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.Column('asset_class', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_nft_token_id'), 'assets', ['nft_token_id'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_verification_token', sa.String(length=128), nullable=False),
    sa.Column('holder_id', sa.String(length=36), nullable=False),
    sa.Column('issuer_org_id', sa.String(length=36), nullable=False),
    sa.Column('issuer_user_id', sa.String(length=36), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issue_date', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('claims_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('anchor_tx_hash', sa.String(length=66), nullable=True),
    sa.CheckConstraint("status IN ('active','expired','revoked','suspended')", name='ck_credentials_status'),
    sa.ForeignKeyConstraint(['holder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issuer_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_api_verification_token'), 'credentials', ['api_verification_token'], unique=True)
    op.create_index(op.f('ix_credentials_holder_id'), 'credentials', ['holder_id'], unique=False)
    op.create_index(op.f('ix_credentials_issuer_org_id'), 'credentials', ['issuer_org_id'], unique=False)
    op.create_index(op.f('ix_credentials_issuer_user_id'), 'credentials', ['issuer_user_id'], unique=False)
    op.create_index(op.f('ix_credentials_status'), 'credentials', ['status'], unique=False)
    op.create_table('device_recoveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_recoveries_user_id'), 'device_recoveries', ['user_id'], unique=False)
    op.create_table('duress_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('risk_signals', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duress_sessions_user_id'), 'duress_sessions', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('offline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('client_ts', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_events_content_hash'), 'offline_events', ['content_hash'], unique=False)
    op.create_index(op.f('ix_offline_events_user_id'), 'offline_events', ['user_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('risk_signals', sa.JSON(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('ip_addr', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_jti'), 'sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('trusted_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_key_id', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('browser', sa.String(length=128), nullable=True),
    sa.Column('os', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_devices_user_id'), 'trusted_devices', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=512), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=False)
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    op.create_table('access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_grants_asset_id'), 'access_grants', ['asset_id'], unique=False)
    op.create_index(op.f('ix_access_grants_requester_id'), 'access_grants', ['requester_id'], unique=False)
    op.create_table('access_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('requester_role', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('min_trust', sa.Integer(), nullable=False),
    sa.Column('location_scope', sa.String(length=255), nullable=True),
    sa.Column('location_strict', sa.Boolean(), nullable=False),
    sa.Column('time_start', sa.String(length=16), nullable=True),
    sa.Column('time_end', sa.String(length=16), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('context_required', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_policies_asset_id'), 'access_policies', ['asset_id'], unique=False)
    op.create_table('access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context_provided', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_asset_id'), 'access_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_access_requests_requester_id'), 'access_requests', ['requester_id'], unique=False)
    op.create_table('asset_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=False),
    sa.Column('to_user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('chain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_transfers_asset_id'), 'asset_transfers', ['asset_id'], unique=False)
    op.create_table('credential_access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('allowed_claims', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.CheckConstraint("status IN ('active','revoked','expired')", name='ck_cr_access_grants_status'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_access_grants_credential_id'), 'credential_access_grants', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credential_access_grants_expires_at'), 'credential_access_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_credential_access_grants_requester_id'), 'credential_access_grants', ['requester_id'], unique=False)
    op.create_index(op.f('ix_credential_access_grants_status'), 'credential_access_grants', ['status'], unique=False)
    op.create_table('credential_access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('requested_claims', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','denied','expired','cancelled')", name='ck_cr_access_requests_status'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_access_requests_credential_id'), 'credential_access_requests', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credential_access_requests_requester_id'), 'credential_access_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_credential_access_requests_status'), 'credential_access_requests', ['status'], unique=False)
    op.create_table('credential_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('claim_key', sa.String(length=128), nullable=False),
    sa.Column('claim_value', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_claims_credential_id'), 'credential_claims', ['credential_id'], unique=False)
    op.create_table('credential_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('detected_type', sa.String(length=128), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_files_credential_id'), 'credential_files', ['credential_id'], unique=False)
    op.create_table('credential_issuers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('issuer_user_id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_issuers_credential_id'), 'credential_issuers', ['credential_id'], unique=False)
    op.create_table('revocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('revoked_by', sa.String(length=36), nullable=False),
    sa.Column('revoke_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('anchor_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revocations_credential_id'), 'revocations', ['credential_id'], unique=False)
    op.create_table('verification_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('verifier_org_id', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("result IN ('VERIFIED','INVALID','EXPIRED','REVOKED')", name='ck_verification_events_result'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_events_credential_id'), 'verification_events', ['credential_id'], unique=False)
    op.create_index(op.f('ix_verification_events_verification_token'), 'verification_events', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_events_verification_token'), table_name='verification_events')
    op.drop_index(op.f('ix_verification_events_credential_id'), table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_index(op.f('ix_revocations_credential_id'), table_name='revocations')
    op.drop_table('revocations')
    op.drop_index(op.f('ix_credential_issuers_credential_id'), table_name='credential_issuers')
    op.drop_table('credential_issuers')
    op.drop_index(op.f('ix_credential_files_credential_id'), table_name='credential_files')
    op.drop_table('credential_files')
    op.drop_index(op.f('ix_credential_claims_credential_id'), table_name='credential_claims')
    op.drop_table('credential_claims')
    op.drop_index(op.f('ix_credential_access_requests_status'), table_name='credential_access_requests')
    op.drop_index(op.f('ix_credential_access_requests_requester_id'), table_name='credential_access_requests')
    op.drop_index(op.f('ix_credential_access_requests_credential_id'), table_name='credential_access_requests')
    op.drop_table('credential_access_requests')
    op.drop_index(op.f('ix_credential_access_grants_status'), table_name='credential_access_grants')
    op.drop_index(op.f('ix_credential_access_grants_requester_id'), table_name='credential_access_grants')
    op.drop_index(op.f('ix_credential_access_grants_expires_at'), table_name='credential_access_grants')
    op.drop_index(op.f('ix_credential_access_grants_credential_id'), table_name='credential_access_grants')
    op.drop_table('credential_access_grants')
    op.drop_index(op.f('ix_asset_transfers_asset_id'), table_name='asset_transfers')
    op.drop_table('asset_transfers')
    op.drop_index(op.f('ix_access_requests_requester_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_asset_id'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_access_policies_asset_id'), table_name='access_policies')
    op.drop_table('access_policies')
    op.drop_index(op.f('ix_access_grants_requester_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_asset_id'), table_name='access_grants')
    op.drop_table('access_grants')
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_trusted_devices_user_id'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_jti'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_offline_events_user_id'), table_name='offline_events')
    op.drop_index(op.f('ix_offline_events_content_hash'), table_name='offline_events')
    op.drop_table('offline_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_duress_sessions_user_id'), table_name='duress_sessions')
    op.drop_table('duress_sessions')
    op.drop_index(op.f('ix_device_recoveries_user_id'), table_name='device_recoveries')
    op.drop_table('device_recoveries')
    op.drop_index(op.f('ix_credentials_status'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_issuer_user_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_issuer_org_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_holder_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_api_verification_token'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_nft_token_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_did'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_official_domain'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_anchors_event_id'), table_name='audit_anchors')
    op.drop_table('audit_anchors')
    # ### end Alembic commands ###
