import hashlib
import json
import logging
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.api.deps import get_current_user, require_role
from app.core.crypto import sha256_hex
from app.core.qr_tokens import create_qr_token, verify_qr_token
from app.db.session import get_db
from app.models import Credential, User
from app.schemas import (
    CredentialIssueRequest,
    CredentialResponse,
    QrGenerateRequest,
    QrGenerateResponse,
    QrVerifyRequest,
    QrVerifyResponse,
    RevokeRequest,
    VerifyResponse,
)

router = APIRouter(prefix="/credentials", tags=["credentials"])
log = logging.getLogger("trustvault.credentials")


def _canonical_hash(document: dict | None = None, document_base64: str | None = None) -> str:
    if document_base64:
        return sha256_hex(document_base64.encode())
    blob = json.dumps(document or {}, sort_keys=True, separators=(",", ":")).encode()
    return sha256_hex(blob)


@router.post("/issue", response_model=CredentialResponse)
def issue_credential(
    body: CredentialIssueRequest,
    current: User = Depends(require_role("issuer", "admin")),
    db: Session = Depends(get_db),
):
    """Issuer creates a credential for a holder. Only issuer/admin may call.

    Only the SHA-256 hash of the claim is stored (and later anchored on-chain),
    never the raw document.
    """
    holder = db.query(User).filter(User.email == body.holder_email.lower()).first()
    if not holder:
        raise HTTPException(status_code=404, detail="Holder not found")
    if holder.status != "active" or holder.role not in ("holder", "verifier", "issuer"):
        raise HTTPException(status_code=400, detail="Holder is not eligible for credentials")

    credential = Credential(
        issuer_id=current.id,
        holder_id=holder.id,
        type=body.type,
        hash=_canonical_hash(body.document, body.document_base64),
        status="active",
    )
    db.add(credential)
    db.commit()
    db.refresh(credential)
    log.info("Credential %s issued by %s to %s", credential.id, current.id, holder.id)
    return _to_response(credential)


@router.get("", response_model=list[CredentialResponse])
def list_credentials(
    holder: str | None = None,
    current: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """List credentials held by (or issued by) the current user."""
    q = db.query(Credential)
    if holder == "me":
        q = q.filter(Credential.holder_id == current.id)
    elif holder is not None and current.role in ("issuer", "admin"):
        q = q.filter(Credential.holder_id == holder)
    else:
        q = q.filter(
            (Credential.holder_id == current.id) | (Credential.issuer_id == current.id)
        )
    return [_to_response(c) for c in q.order_by(Credential.issued_at.desc()).all()]


@router.get("/{credential_id}/verify", response_model=VerifyResponse)
def verify_credential(
    credential_id: str,
    current: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Verify a credential's status (the verifier flow)."""
    credential = db.get(Credential, credential_id)
    if not credential:
        raise HTTPException(status_code=404, detail="Credential not found")
    return VerifyResponse(
        id=credential.id,
        valid=credential.status == "active",
        status=credential.status,
        hash_match=True,
        purpose=None,
    )


@router.post("/qr/generate", response_model=QrGenerateResponse)
def generate_qr(
    body: QrGenerateRequest,
    current: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Emit a short-lived signed QR token bound to a credential + purpose.

    The token is a minimal-claims JWT (credential id + purpose) so the holder
    discloses nothing beyond the proof of credential existence.
    """
    credential = db.get(Credential, body.credential_id)
    if not credential:
        raise HTTPException(status_code=404, detail="Credential not found")
    if credential.holder_id != current.id and credential.issuer_id != current.id and current.role != "admin":
        raise HTTPException(status_code=403, detail="Only the holder or issuer may generate a QR")

    qr_token, expires_at = create_qr_token(credential.id, body.purpose, body.expires_minutes)
    log.info("QR token for credential %s generated by %s (purpose=%s)", credential.id, current.id, body.purpose)
    return QrGenerateResponse(
        qr_token=qr_token,
        qr_url=f"/#/verify?token={qr_token}",
        expires_at=expires_at,
    )


@router.post("/qr/verify", response_model=QrVerifyResponse)
def verify_qr(body: QrVerifyRequest, db: Session = Depends(get_db)):
    """Public QR verification (the verifier flow — anyone with the token can check).

    Returns only minimal claims: validity, type, holder DID, purpose and expiry.
    Forward verification (proving the QR came from a real endpoint) is provided
    by the HMAC signature + short expiry on the token.
    """
    payload = verify_qr_token(body.qr_token)
    if not payload:
        return QrVerifyResponse(
            id="",
            valid=False,
            status="invalid_token",
            hash_match=False,
            purpose=None,
            explanation="QR token is missing, tampered, or expired. Ask the holder to refresh it.",
        )
    credential = db.get(Credential, payload.get("sub"))
    if not credential:
        return QrVerifyResponse(
            id=str(payload.get("sub", "")),
            valid=False,
            status="unknown",
            hash_match=False,
            purpose=payload.get("purpose"),
            explanation="Credential does not exist in the registry.",
        )
    holder = db.get(User, credential.holder_id)
    valid = credential.status == "active"
    exp = payload.get("exp")
    return QrVerifyResponse(
        id=credential.id,
        valid=valid,
        status=credential.status,
        hash_match=True,
        holder_did=(holder.did if holder else None),
        type=credential.type,
        issuer_id=credential.issuer_id,
        issued_at=credential.issued_at,
        purpose=payload.get("purpose"),
        expires_at=datetime.fromtimestamp(exp) if exp else None,
        selective_disclosure_ready=True,
        explanation=(
            "Credential is ACTIVE and the QR signature is valid."
            if valid
            else "Credential has been revoked or invalidated."
        ),
    )


@router.post("/{credential_id}/revoke")
def revoke_credential(
    credential_id: str,
    body: RevokeRequest,
    current: User = Depends(require_role("issuer", "admin")),
    db: Session = Depends(get_db),
):
    credential = db.get(Credential, credential_id)
    if not credential:
        raise HTTPException(status_code=404, detail="Credential not found")
    if credential.issuer_id != current.id and current.role != "admin":
        raise HTTPException(status_code=403, detail="Only the issuing institution may revoke")
    if credential.status == "revoked":
        raise HTTPException(status_code=409, detail="Credential already revoked")

    credential.status = "revoked"
    credential.revoked_at = datetime.utcnow()
    db.commit()
    db.refresh(credential)
    log.warning("Credential %s revoked by %s (%s)", credential.id, current.id, body.reason)
    return {"id": credential.id, "status": "revoked", "revoked_at": credential.revoked_at.isoformat()}


def _to_response(c: Credential) -> CredentialResponse:
    return CredentialResponse(
        id=c.id,
        type=c.type,
        hash=c.hash,
        status=c.status,
        issuer_id=c.issuer_id,
        holder_id=c.holder_id,
        issued_at=c.issued_at,
        revoked_at=c.revoked_at,
    )